---

_docker_distro_packages:
  - docker

_docker_upstream_distro_required_packages:
  - dnf-plugins-core

_docker_upstream_distro_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_repo_template: docker-ce-fedora.repo.j2

docker_distro_vars_loaded: true

_docker_mirror_base_url: "https://{{ docker_download_fqdn }}/linux/fedora"
