- hosts: all
  roles:
    - role: clear-firewall
    - role: ensure-kubernetes
      vars:
        minikube_dns_resolvers:
          - '1.1.1.1'
          - '8.8.8.8'
        kubernetes_runtime: cri-o
    - role: use-buildset-registry
      buildset_registry_docker_user: root
  tasks:
    - name: Wait for cluster to come up
      command: kubectl cluster-info
      register: result
      until: result.rc == 0
      retries: 5
      delay: 30
    - name: Run a local test pod
      command: kubectl run --generator=run-pod/v1 --image=quay.io/zuul/quay-testimage quaytest
    - name: Wait for the pod to be ready
      command: kubectl wait --for=condition=Ready pod/quaytest --timeout=60s
    - name: Check the output of the pod
      shell: "kubectl logs pod/quaytest | grep 'Zuul container test'"
      args:
        warn: false

    - name: Run a remote test pod
      command: kubectl run --generator=run-pod/v1 --image=docker.io/debian:testing upstream-dockertest --command -- /bin/bash -c 'echo Upstream; sleep infinity'
    - name: Wait for the pod to be ready
      command: kubectl wait --for=condition=Ready pod/upstream-dockertest --timeout=60s
    - name: Check the output of the pod
      shell: "kubectl logs pod/upstream-dockertest | grep 'Upstream'"
      args:
        warn: false
